// Account Settings
export const CHANGE_PASSWORD = {
    ATTEMPT: 'CHANGE_PASSWORD_ATTEMPT',
    FAILED: 'CHANGE_PASSWORD_FAILED',
    RESET: 'CHANGE_PASSWORD_RESET',
    SUCCEED: 'CHANGE_PASSWORD_SUCCEED'
}

export const CREATE_ADDRESS = {
    ATTEMPT: 'CREATE_ADDRESS_ATTEMPT',
    FAILED: 'CREATE_ADDRESS_FAILED',
    RESET: 'CREATE_ADDRESS_RESET',
    SUCCEED: 'CREATE_ADDRESS_SUCCEED'
}

export const DELETE_ADDRESS = {
    ATTEMPT: 'DELETE_ADDRESS_ATTEMPT',
    FAILED: 'DELETE_ADDRESS_FAILED',
    SUCCEED: 'DELETE_ADDRESS_SUCCEED'
}

export const GET_ADDRESS = {
    ATTEMPT: 'GET_ADDRESS_ATTEMPT',
    FAILED: 'GET_ADDRESS_FAILED',
    SUCCEED: 'GET_ADDRESS_SUCCEED'
}

export const GET_CITIES = {
    ATTEMPT: 'GET_CITIES_ATTEMPT',
    FAILED: 'GET_CITIES_FAILED',
    SUCCEED: 'GET_CITIES_SUCCEED'
}

export const GET_DEFAULT_ADDRESS = {
    ATTEMPT: 'GET_DEFAULT_ADDRESS_ATTEMPT',
    FAILED: 'GET_DEFAULT_ADDRESS_FAILED',
    SUCCEED: 'GET_DEFAULT_ADDRESS_SUCCEED'
}

export const GET_PROFILE = {
    ATTEMPT: 'GET_PROFILE_ATTEMPT',
    FAILED: 'GET_PROFILE_FAILED',
    SUCCEED: 'GET_PROFILE_SUCCEED'
}

export const GET_PROVINCES = {
    ATTEMPT: 'GET_PROVINCES_ATTEMPT',
    FAILED: 'GET_PROVINCES_FAILED',
    SUCCEED: 'GET_PROVINCES_SUCCEED'
}

export const GET_SUBDISTRICTS = {
    ATTEMPT: 'GET_SUBDISTRICTS_ATTEMPT',
    FAILED: 'GET_SUBDISTRICTS_FAILED',
    SUCCEED: 'GET_SUBDISTRICTS_SUCCEED'
}

export const UPDATE_ADDRESS = {
    ATTEMPT: 'UPDATE_ADDRESS_ATTEMPT',
    FAILED: 'UPDATE_ADDRESS_FAILED',
    RESET: 'UPDATE_ADDRESS_RESET',
    SUCCEED: 'UPDATE_ADDRESS_SUCCEED'
}

export const UPDATE_PROFILE = {
    ATTEMPT: 'UPDATE_PROFILE_ATTEMPT',
    FAILED: 'UPDATE_PROFILE_FAILED',
    RESET: 'UPDATE_PROFILE_RESET',
    SUCCEED: 'UPDATE_PROFILE_SUCCEED'
}


// Authentication
export const LOGIN = {
    ATTEMPT: 'LOGIN_ATTEMPT',
    FAILED: 'LOGIN_FAILED',
    SUCCEED: 'LOGIN_SUCCEED'
}

export const LOGOUT = {
    ATTEMPT: 'LOGOUT_ATTEMPT',
    FAILED: 'LOGOUT_FAILED',
    SUCCEED: 'LOGOUT_SUCCEED'
}

export const REGISTER = {
    ATTEMPT: 'REGISTER_ATTEMPT',
    FAILED: 'REGISTER_FAILED',
    SUCCEED: 'REGISTER_SUCCEED'
}

export const REQUEST_OTP = {
    ATTEMPT: 'REQUEST_OTP_ATTEMPT',
    FAILED: 'REQUEST_OTP_FAILED',
    SUCCEED: 'REQUEST_OTP_SUCCEED'
}

export const RESET_PASSWORD = {
    ATTEMPT: 'RESET_PASSWORD_ATTEMPT',
    FAILED: 'RESET_PASSWORD_FAILED',
    SUCCEED: 'RESET_PASSWORD_SUCCEED'
}

export const VERIFY_WITH_OTP = {
    ATTEMPT: 'VERIFY_WITH_OTP_ATTEMPT',
    FAILED: 'VERIFY_WITH_OTP_FAILED',
    SUCCEED: 'VERIFY_WITH_OTP_SUCCEED'
}


// General
export const ADD_OR_SUBTRACT_CART = {
    ATTEMPT: 'ADD_OR_SUBTRACT_CART_ATTEMPT',
    FAILED: 'ADD_OR_SUBTRACT_CART_FAILED',
    SUCCEED: 'ADD_OR_SUBTRACT_CART_SUCCEED'
}

export const GET_CART_DATA = {
    ATTEMPT: 'GET_CART_DATA_ATTEMPT',
    FAILED: 'GET_CART_DATA_FAILED',
    SUCCEED: 'GET_CART_DATA_SUCCEED'
}

export const GET_TOTAL_CART_DATA = {
    ATTEMPT: 'GET_TOTAL_CART_DATA_ATTEMPT',
    FAILED: 'GET_TOTAL_CART_DATA_FAILED',
    SUCCEED: 'GET_TOTAL_CART_DATA_SUCCEED'
}

export const REMOVE_FROM_CART = {
    ATTEMPT: 'REMOVE_FROM_CART_ATTEMPT',
    FAILED: 'REMOVE_FROM_CART_FAILED',
    SUCCEED: 'REMOVE_FROM_CART_SUCCEED'
}


// Home
export const GET_HOME_DATA = {
    ATTEMPT: 'GET_HOME_DATA_ATTEMPT',
    FAILED: 'GET_HOME_DATA_FAILED',
    SUCCEED: 'GET_HOME_DATA_SUCCEED'
}


// Product
export const ADD_WISHLIST = {
    ATTEMPT: 'ADD_WISHLIST_ATTEMPT',
    FAILED: 'ADD_WISHLIST_FAILED',
    SUCCEED: 'ADD_WISHLIST_SUCCEED'
}

export const GET_PRODUCT_DETAIL = {
    ATTEMPT: 'GET_PRODUCT_DETAIL_ATTEMPT',
    FAILED: 'GET_PRODUCT_DETAIL_FAILED',
    SUCCEED: 'GET_PRODUCT_DETAIL_SUCCEED'
}

export const GET_PRODUCTS = {
    ATTEMPT: 'GET_PRODUCTS_ATTEMPT',
    FAILED: 'GET_PRODUCTS_FAILED',
    SUCCEED: 'GET_PRODUCTS_SUCCEED'
}

export const GET_WISHLISTS = {
    ATTEMPT: 'GET_WISHLISTS_ATTEMPT',
    FAILED: 'GET_WISHLISTS_FAILED',
    SUCCEED: 'GET_WISHLISTS_SUCCEED'
}

export const REMOVE_WISHLIST = {
    ATTEMPT: 'REMOVE_WISHLIST_ATTEMPT',
    FAILED: 'REMOVE_WISHLIST_FAILED',
    SUCCEED: 'REMOVE_WISHLIST_SUCCEED'
}


// Transaction
export const CONFIRM_RECEIVE = {
    ATTEMPT: 'CONFIRM_RECEIVE_ATTEMPT',
    FAILED: 'CONFIRM_RECEIVE_FAILED',
    SUCCEED: 'CONFIRM_RECEIVE_SUCCEED'
}

export const GET_ORDER_DETAIL = {
    ATTEMPT: 'GET_ORDER_DETAIL_ATTEMPT',
    FAILED: 'GET_ORDER_DETAIL_FAILED',
    SUCCEED: 'GET_ORDER_DETAIL_SUCCEED'
}

export const GET_TRANSACTIONS = {
    ATTEMPT: 'GET_TRANSACTIONS_ATTEMPT',
    FAILED: 'GET_TRANSACTIONS_FAILED',
    SUCCEED: 'GET_TRANSACTIONS_SUCCEED'
}

export const TRACK_SHIPMENT = {
    ATTEMPT: 'TRACK_SHIPMENT_ATTEMPT',
    FAILED: 'TRACK_SHIPMENT_FAILED',
    SUCCEED: 'TRACK_SHIPMENT_SUCCEED'
}